version: '2'
services:
  mysql:
    container_name: doowiki-mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password' # TODO: Change this
      MYSQL_DATABASE: 'doowiki'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'telogreika'
    volumes:
      - $USERPROFILE\doowiki-volume:/var/lib/mysql
    ports:
      - "3306:3306"
  doowiki:
    container_name: doowiki-app
    restart: always
    image: doowiki
    environment: 
      ConnectionStrings__doowiki-mysql: 'server=mysql;uid=dev;pwd=telogreika;database=doowiki'
    ports:
      - '8080:8080'