version: '2'
services:
  mysql:
    container_name: doowiki-mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password' # TODO: Change this
      MYSQL_DATABASE: 'doowiki'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'telogreika'
    volumes:
      - $USERPROFILE\doowiki-volume:/var/lib/mysql
    ports:
      - "3306:3306"